[[redirects]]
  from = "/.well-known/apple-app-site-association"
  to = "/apple-app-site-association"
  status = 200

[[headers]]
  for = "/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
