[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/.well-known/apple-app-site-association"
  to = "/apple-app-site-association"
  status = 200
  force = true

[[headers]]
  for = "/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
